# Generated by Django 2.2.4 on 2019-12-05 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupon',
            options={'ordering': ('active',), 'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
        migrations.AlterField(
            model_name='cupon',
            name='active',
            field=models.BooleanField(verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Код купона'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='discount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Размер скидки'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Действителен с'),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Действителен до'),
        ),
    ]
