# Generated by Django 2.2.4 on 2019-10-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190924_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_paid',
            field=models.BooleanField(default=True),
        ),
    ]
