# Generated by Django 2.2.4 on 2019-10-24 22:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_card_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_order',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
