# Generated by Django 2.2.4 on 2019-10-24 23:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_phone_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_order',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
