# Generated by Django 2.2.4 on 2019-10-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191025_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_processed',
            field=models.BooleanField(default=False),
        ),
    ]
